apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: product-service-prod
resources:
  - ../../base
  - rollout.yaml
#  blueGreen 사용시
#  - product-service-active.yaml
#  - product-service-preview.yaml
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: product-service
      $patch: delete
#  - patch: |-
#      apiVersion: v1
#      kind: Service
#      metadata:
#        name: product-service
#      $patch: delete
images:
  - name: product-service
    newTag: "v3"